### ISSUE TITLE
Error when killing Zombies

### ISSUE THREAD

**Issue by raawkins** [cyberbobjr/BATMAN_EHE_MILITARY_DROP#1]
Hello, i get an error when killing what i suppose to be zombies carrying the supposed note drop.

Things that i've tried to solve the issue.

1) Resubscribe
2) Different load orders.

> function:` HTC_OnZombieDead -- file: HTC_EHE_NoteDrop.lua line # 44 | MOD: [HERE THEY COME] - Expanded Helicopter Event - Military Drop
> 
> java.lang.RuntimeException: __concat not defined for operands: HTC - EHE: HTC_OnZombieDead  and null
>     at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
>     at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:805)
>     at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
>     at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
>     at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
>     at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
>     at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
>     at zombie.Lua.Event.trigger(Event.java:64)
>     at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
>     at zombie.characters.IsoZombie.Kill(IsoZombie.java:5115)
>     at zombie.characters.IsoZombie.Kill(IsoZombie.java:5129)
>     at zombie.characters.IsoGameCharacter.hitConsequences(IsoGameCharacter.java:6731)
>     at zombie.characters.IsoZombie.hitConsequences(IsoZombie.java:3528)
>     at zombie.characters.IsoGameCharacter.Hit(IsoGameCharacter.java:6537)
>     at zombie.characters.IsoZombie.Hit(IsoZombie.java:928)
>     at zombie.characters.IsoGameCharacter.Hit(IsoGameCharacter.java:6398)
>     at zombie.ai.states.SwipeStatePlayer.ConnectSwing(SwipeStatePlayer.java:2097)
>     at zombie.ai.states.SwipeStatePlayer.animEvent(SwipeStatePlayer.java:392)
>     at zombie.ai.StateMachine.lambda$stateAnimEvent$6(StateMachine.java:268)
>     at zombie.util.lambda.Consumers$Params2$CallbackStackItem.accept(Consumers.java:93)
>     at zombie.util.list.PZArrayUtil.forEach(PZArrayUtil.java:904)
>     at zombie.util.Lambda.lambda$forEachFrom$3(Lambda.java:219)
>     at zombie.util.lambda.Stacks$Params5$CallbackStackItem.invoke(Stacks.java:345)
>     at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
>     at zombie.util.Lambda.capture(Lambda.java:142)
>     at zombie.util.Lambda.forEachFrom(Lambda.java:216)
>     at zombie.ai.StateMachine.stateAnimEvent(StateMachine.java:264)
>     at zombie.characters.IsoGameCharacter.OnAnimEvent(IsoGameCharacter.java:4235)
>     at zombie.characters.IsoPlayer.OnAnimEvent(IsoPlayer.java:9401)
>     at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.OnAnimEvent(AdvancedAnimator.java:264)
>     at zombie.core.skinnedmodel.advancedanimation.AnimLayer.invokeAnimEvent(AnimLayer.java:211)
>     at zombie.core.skinnedmodel.advancedanimation.AnimLayer.updateInternal(AnimLayer.java:419)
>     at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
>     at zombie.core.skinnedmodel.advancedanimation.AnimLayer.Update(AnimLayer.java:323)
>     at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator$SubLayerSlot.update(AdvancedAnimator.java:665)
>     at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.updateInternal(AdvancedAnimator.java:403)
>     at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
>     at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.update(AdvancedAnimator.java:368)
>     at zombie.characters.IsoGameCharacter.postUpdateInternal(IsoGameCharacter.java:12087)
>     at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
>     at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
>     at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
>     at zombie.util.Lambda.capture(Lambda.java:130)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
>     at zombie.characters.IsoGameCharacter.postupdate(IsoGameCharacter.java:12063)
>     at zombie.characters.IsoPlayer.postupdateInternal(IsoPlayer.java:3740)
>     at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
>     at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
>     at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
>     at zombie.util.Lambda.capture(Lambda.java:130)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
>     at zombie.characters.IsoPlayer.postupdate(IsoPlayer.java:3733)
>     at zombie.MovingObjectUpdateSchedulerUpdateBucket.postupdate(MovingObjectUpdateSchedulerUpdateBucket.java:97)
>     at zombie.MovingObjectUpdateScheduler.postupdate(MovingObjectUpdateScheduler.java:168)
>     at zombie.CollisionManager.resolveContactsInternal(CollisionManager.java:411)
>     at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
>     at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
>     at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
>     at zombie.util.Lambda.capture(Lambda.java:130)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
>     at zombie.CollisionManager.ResolveContacts(CollisionManager.java:236)
>     at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3502)
>     at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
>     at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
>     at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
>     at zombie.util.Lambda.capture(Lambda.java:130)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
>     at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
>     at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
>     at zombie.gameStates.IngameState.update(IngameState.java:1333)
>     at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
>     at zombie.GameWindow.logic(GameWindow.java:298)
>     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
>     at zombie.GameWindow.frameStep(GameWindow.java:765)
>     at zombie.GameWindow.run_ez(GameWindow.java:681)
>     at zombie.GameWindow.mainThread(GameWindow.java:495)
>     at java.base/java.lang.Thread.run(Unknown Source)

**Comment by cyberbobjr** [comment]
Thanks for your report i'll check for that

**Comment by cyberbobjr** [comment]
can you send me the list of mods used please ?
